# # # import sqlite3
# # # from datetime import datetime

# # # import pandas as pd

# # # from src.core.state import InventoryItem, MarketEvent, MaterialCatalog, SystemState, SupplierProfile


# # # def load_state_from_db(db_path: str = "data/inventory.db") -> SystemState:
# # #     conn = sqlite3.connect(db_path)

# # #     inv_df = pd.read_sql("SELECT * FROM inventory", conn)
# # #     inventory = {}
# # #     for _, row in inv_df.iterrows():
# # #         mid = row["material_id"]
# # #         inventory.setdefault(mid, []).append(
# # #             InventoryItem(
# # #                 location=row["location"],
# # #                 quantity=float(row["quantity"]),
# # #                 safety_stock=float(row["safety_stock"]),
# # #                 expiry_days=int(row["expiry_days"]),
# # #             )
# # #         )

# # #     mat_df = pd.read_sql("SELECT * FROM materials", conn)
# # #     catalog = {}
# # #     for _, row in mat_df.iterrows():
# # #         catalog[row["material_id"]] = MaterialCatalog(
# # #             unit_price=float(row["unit_cost"]),
# # #             stockout_penalty=float(row["stockout_penalty"]),
# # #             holding_cost_rate=float(row["holding_cost_rate"]),
# # #             expiry_penalty=float(row["expiry_penalty"]),
# # #         )

# # #     sup_df = pd.read_sql("SELECT * FROM suppliers", conn)
# # #     suppliers = {}
# # #     for _, row in sup_df.iterrows():
# # #         suppliers[row["supplier_id"]] = SupplierProfile(
# # #             name=row["name"],
# # #             lead_time_mean=float(row["lead_time_mean"]),
# # #             lead_time_std=float(row["lead_time_std"]),
# # #             reliability=float(row["reliability"]),
# # #             cost_multiplier=float(row["cost_multiplier"]),
# # #             observed_delays=(),
# # #         )

# # #     hist_df = pd.read_sql("SELECT material_id, demand_units FROM demand_history ORDER BY date", conn)
# # #     demand_history = {}
# # #     for mid in inventory.keys():
# # #         demand_history[mid] = hist_df[hist_df["material_id"] == mid]["demand_units"].astype(float).tolist()

# # #     market_events = []
# # #     try:
# # #         ev_df = pd.read_sql("SELECT * FROM market_events", conn)
# # #         for _, row in ev_df.iterrows():
# # #             market_events.append(
# # #                 MarketEvent(
# # #                     material_id=row["material_id"],
# # #                     start_day=int(row["start_day"]),
# # #                     duration_days=int(row["duration_days"]),
# # #                     multiplier=float(row["multiplier"]),
# # #                     event_type=row["event_type"],
# # #                 )
# # #             )
# # #     except Exception:
# # #         market_events = []

# # #     conn.close()

# # #     return SystemState(
# # #         timestamp=datetime.now(),
# # #         inventory=inventory,
# # #         in_transit=[],
# # #         suppliers=suppliers,
# # #         catalog=catalog,
# # #         demand_history=demand_history,
# # #         market_events=market_events,
# # #         budget_remaining=100000.0,
# # #         window_demand={},
# # #         window_fulfilled={},
# # #     )

# # """
# # Load a SystemState from the SQLite database generated by generate_database.py.
# # """
# # from __future__ import annotations
# # import sqlite3
# # from typing import Dict, List

# # import pandas as pd

# # from src.core.state import InventoryItem, MaterialCatalog, MarketEvent, SupplierProfile, SystemState


# # def load_state_from_db(db_path: str = "data/inventory.db") -> SystemState:
# #     conn = sqlite3.connect(db_path)

# #     # ---------- Materials / Catalog ----------
# #     mats = pd.read_sql("SELECT * FROM materials", conn)
# #     catalog: Dict[str, MaterialCatalog] = {}
# #     for _, row in mats.iterrows():
# #         catalog[row["material_id"]] = MaterialCatalog(
# #             unit_price=row["unit_cost"],
# #             stockout_penalty=row["stockout_penalty"],
# #             holding_cost_rate=row["holding_cost_rate"],
# #             expiry_penalty=row["expiry_penalty"],
# #         )

# #     # ---------- Suppliers ----------
# #     sups = pd.read_sql("SELECT * FROM suppliers", conn)
# #     suppliers: Dict[str, SupplierProfile] = {}
# #     for _, row in sups.iterrows():
# #         sup = SupplierProfile(
# #             name=row["name"],
# #             lead_time_mean=row["lead_time_mean"],
# #             lead_time_std=row["lead_time_std"],
# #             reliability=row["reliability"],
# #         )
# #         # Attach cost_multiplier as dynamic attribute (not in dataclass)
# #         sup.__dict__["cost_multiplier"] = row["cost_multiplier"]
# #         suppliers[row["supplier_id"]] = sup

# #     # ---------- Inventory ----------
# #     inv_df = pd.read_sql("SELECT * FROM inventory", conn)
# #     inventory: Dict[str, List[InventoryItem]] = {}
# #     for _, row in inv_df.iterrows():
# #         mid = row["material_id"]
# #         item = InventoryItem(
# #             location=row["location"],
# #             quantity=float(row["quantity"]),
# #             safety_stock=float(row["safety_stock"]),
# #             expiry_days=int(row["expiry_days"]) if row["expiry_days"] is not None else None,
# #         )
# #         inventory.setdefault(mid, []).append(item)

# #     # ---------- Demand History ----------
# #     dem_df = pd.read_sql(
# #         "SELECT material_id, demand_units FROM demand_history ORDER BY date ASC", conn
# #     )
# #     demand_history: Dict[str, List[float]] = {}
# #     for _, row in dem_df.iterrows():
# #         demand_history.setdefault(row["material_id"], []).append(float(row["demand_units"]))

# #     # ---------- Market Events ----------
# #     ev_df = pd.read_sql("SELECT * FROM market_events", conn)
# #     market_events: List[MarketEvent] = []
# #     for _, row in ev_df.iterrows():
# #         market_events.append(MarketEvent(
# #             material_id=row["material_id"],
# #             multiplier=float(row["multiplier"]),
# #             duration_days=int(row["duration_days"]),
# #             event_type=row["event_type"],
# #         ))

# #     conn.close()

# #     return SystemState(
# #         inventory=inventory,
# #         suppliers=suppliers,
# #         catalog=catalog,
# #         market_events=market_events,
# #         demand_history=demand_history,
# #         budget_remaining=100_000.0,
# #         current_day=0,
# #     )
# """
# db_loader.py
# ============
# Load SystemState from inventory.db.
# Also provides load_scenarios() and apply_scenario() for the demo scenario system.
# """
# from __future__ import annotations
# import copy
# import json
# import sqlite3
# from typing import Dict, List, Optional

# import numpy as np
# import pandas as pd

# from src.core.state import (
#     InventoryItem, MaterialCatalog, MarketEvent,
#     SupplierProfile, SystemState,
# )


# # ─────────────────────────────────────────────────────────────────────────────
# #  BASE STATE LOADER
# # ─────────────────────────────────────────────────────────────────────────────

# def load_state_from_db(db_path: str = "data/inventory.db") -> SystemState:
#     conn = sqlite3.connect(db_path)

#     # Materials / Catalog
#     catalog: Dict[str, MaterialCatalog] = {}
#     for row in conn.execute("SELECT * FROM materials").fetchall():
#         mid = row[0]
#         catalog[mid] = MaterialCatalog(
#             unit_price        = row[2],
#             stockout_penalty  = row[3],
#             holding_cost_rate = row[4],
#             expiry_penalty    = row[5],
#         )

#     # Suppliers
#     suppliers: Dict[str, SupplierProfile] = {}
#     for row in conn.execute("SELECT * FROM suppliers").fetchall():
#         sup = SupplierProfile(
#             name            = row[1],
#             lead_time_mean  = row[2],
#             lead_time_std   = row[3],
#             reliability     = row[4],
#         )
#         sup.__dict__["cost_multiplier"] = row[5]
#         suppliers[row[0]] = sup

#     # Inventory
#     inventory: Dict[str, List[InventoryItem]] = {}
#     for row in conn.execute("SELECT * FROM inventory").fetchall():
#         mid  = row[0]
#         item = InventoryItem(
#             location    = row[1],
#             quantity    = float(row[2]),
#             safety_stock= float(row[3]),
#             expiry_days = int(row[4]) if row[4] is not None else None,
#         )
#         inventory.setdefault(mid, []).append(item)

#     # Demand History
#     demand_history: Dict[str, List[float]] = {}
#     for row in conn.execute(
#         "SELECT material_id, demand_units FROM demand_history ORDER BY date ASC"
#     ).fetchall():
#         demand_history.setdefault(row[0], []).append(float(row[1]))

#     # Market Events (base — usually empty; scenarios inject their own)
#     market_events: List[MarketEvent] = []
#     for row in conn.execute("SELECT * FROM market_events").fetchall():
#         market_events.append(MarketEvent(
#             material_id  = row[0],
#             multiplier   = float(row[3]),
#             duration_days= int(row[2]),
#             event_type   = row[4],
#         ))

#     conn.close()

#     return SystemState(
#         inventory      = inventory,
#         suppliers      = suppliers,
#         catalog        = catalog,
#         market_events  = market_events,
#         demand_history = demand_history,
#         budget_remaining = 100_000.0,
#         current_day    = 0,
#     )


# # ─────────────────────────────────────────────────────────────────────────────
# #  SCENARIO LOADER
# # ─────────────────────────────────────────────────────────────────────────────

# def load_scenarios(db_path: str = "data/inventory.db") -> List[Dict]:
#     """Return all scenarios as a list of dicts."""
#     conn = sqlite3.connect(db_path)
#     try:
#         rows = conn.execute("SELECT * FROM scenarios ORDER BY scenario_id").fetchall()
#         cols = [d[0] for d in conn.execute("SELECT * FROM scenarios LIMIT 0").description]
#         return [dict(zip(cols, r)) for r in rows]
#     except Exception:
#         return []
#     finally:
#         conn.close()


# def apply_scenario(scenario: Dict, base_state: SystemState) -> SystemState:
#     """
#     Apply a scenario config to a deep clone of base_state.
#     Returns a modified SystemState — base_state is never mutated.

#     config_json fields:
#         inventory_overrides: list of
#             { material_id, location ("ALL" or specific), quantity_pct_of_safety, expiry_days }
#         market_events: list of
#             { material_id, multiplier, duration_days, event_type }
#         budget_override: float (optional)
#     """
#     s   = base_state.deep_clone()
#     cfg = json.loads(scenario.get("config_json", "{}"))

#     # ── Inventory overrides ───────────────────────────────────────────────────
#     for ov in cfg.get("inventory_overrides", []):
#         mid      = ov["material_id"]
#         loc      = ov.get("location", "ALL")
#         pct      = float(ov.get("quantity_pct_of_safety", 1.0))
#         exp_days = ov.get("expiry_days")          # None = keep existing

#         if mid not in s.inventory:
#             continue

#         for item in s.inventory[mid]:
#             if loc == "ALL" or item.location == loc:
#                 item.quantity = max(0.0, item.safety_stock * pct)
#                 if exp_days is not None:
#                     item.expiry_days = int(exp_days)

#     # ── Market events ─────────────────────────────────────────────────────────
#     new_events = []
#     for ev in cfg.get("market_events", []):
#         new_events.append(MarketEvent(
#             material_id  = ev["material_id"],
#             multiplier   = float(ev["multiplier"]),
#             duration_days= int(ev["duration_days"]),
#             event_type   = ev["event_type"],
#         ))
#     s.market_events = new_events

#     # ── Budget override ───────────────────────────────────────────────────────
#     if "budget_override" in cfg:
#         s.budget_remaining = float(cfg["budget_override"])

#     return s

"""
db_loader.py
============
Load SystemState from inventory.db.
Also provides load_scenarios() and apply_scenario() for the demo scenario system.
"""
from __future__ import annotations
import copy
import json
import sqlite3
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from src.core.state import (
    InventoryItem, MaterialCatalog, MarketEvent,
    SupplierProfile, SystemState,
)


# ─────────────────────────────────────────────────────────────────────────────
#  BASE STATE LOADER
# ─────────────────────────────────────────────────────────────────────────────

def load_state_from_db(db_path: str = "data/inventory.db") -> SystemState:
    conn = sqlite3.connect(db_path)

    # Materials / Catalog
    catalog: Dict[str, MaterialCatalog] = {}
    for row in conn.execute("SELECT * FROM materials").fetchall():
        mid = row[0]
        catalog[mid] = MaterialCatalog(
            unit_price        = row[2],
            stockout_penalty  = row[3],
            holding_cost_rate = row[4],
            expiry_penalty    = row[5],
        )

    # Suppliers
    suppliers: Dict[str, SupplierProfile] = {}
    for row in conn.execute("SELECT * FROM suppliers").fetchall():
        sup = SupplierProfile(
            name            = row[1],
            lead_time_mean  = row[2],
            lead_time_std   = row[3],
            reliability     = row[4],
        )
        sup.__dict__["cost_multiplier"] = row[5]
        suppliers[row[0]] = sup

    # Inventory
    inventory: Dict[str, List[InventoryItem]] = {}
    for row in conn.execute("SELECT * FROM inventory").fetchall():
        mid  = row[0]
        item = InventoryItem(
            location    = row[1],
            quantity    = float(row[2]),
            safety_stock= float(row[3]),
            expiry_days = int(row[4]) if row[4] is not None else None,
        )
        inventory.setdefault(mid, []).append(item)

    # Demand History
    demand_history: Dict[str, List[float]] = {}
    for row in conn.execute(
        "SELECT material_id, demand_units FROM demand_history ORDER BY date ASC"
    ).fetchall():
        demand_history.setdefault(row[0], []).append(float(row[1]))

    # Market Events (base — usually empty; scenarios inject their own)
    market_events: List[MarketEvent] = []
    for row in conn.execute("SELECT * FROM market_events").fetchall():
        market_events.append(MarketEvent(
            material_id  = row[0],
            multiplier   = float(row[3]),
            duration_days= int(row[2]),
            event_type   = row[4],
        ))

    conn.close()

    return SystemState(
        inventory      = inventory,
        suppliers      = suppliers,
        catalog        = catalog,
        market_events  = market_events,
        demand_history = demand_history,
        budget_remaining = 100_000.0,
        current_day    = 0,
    )


# ─────────────────────────────────────────────────────────────────────────────
#  SCENARIO LOADER
# ─────────────────────────────────────────────────────────────────────────────

def load_scenarios(db_path: str = "data/inventory.db") -> List[Dict]:
    """Return all scenarios as a list of dicts."""
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute("SELECT * FROM scenarios ORDER BY scenario_id").fetchall()
        cols = [d[0] for d in conn.execute("SELECT * FROM scenarios LIMIT 0").description]
        return [dict(zip(cols, r)) for r in rows]
    except Exception:
        return []
    finally:
        conn.close()


def apply_scenario(scenario: Dict, base_state: SystemState) -> SystemState:
    """
    Apply a scenario config to a deep clone of base_state.
    Returns a modified SystemState — base_state is never mutated.

    config_json fields:
        inventory_overrides: list of
            { material_id, location ("ALL" or specific), quantity_pct_of_safety, expiry_days }
        market_events: list of
            { material_id, multiplier, duration_days, event_type }
        budget_override: float (optional)
    """
    s   = base_state.deep_clone()
    cfg = json.loads(scenario.get("config_json", "{}"))

    # ── Inventory overrides ───────────────────────────────────────────────────
    for ov in cfg.get("inventory_overrides", []):
        mid      = ov["material_id"]
        loc      = ov.get("location", "ALL")
        pct      = float(ov.get("quantity_pct_of_safety", 1.0))
        exp_days = ov.get("expiry_days")          # None = keep existing

        if mid not in s.inventory:
            continue

        for item in s.inventory[mid]:
            if loc == "ALL" or item.location == loc:
                item.quantity = max(0.0, item.safety_stock * pct)
                if exp_days is not None:
                    item.expiry_days = int(exp_days)

    # ── Market events ─────────────────────────────────────────────────────────
    new_events = []
    for ev in cfg.get("market_events", []):
        new_events.append(MarketEvent(
            material_id  = ev["material_id"],
            multiplier   = float(ev["multiplier"]),
            duration_days= int(ev["duration_days"]),
            event_type   = ev["event_type"],
        ))
    s.market_events = new_events

    # ── Budget override ───────────────────────────────────────────────────────
    if "budget_override" in cfg:
        s.budget_remaining = float(cfg["budget_override"])

    return s